wifi_ssid: "YOUR_WIFI_SSID"
wifi_password: "YOUR_WIFI_PASSWORD"

api_encryption_key_zone_a: "REPLACE_WITH_YOUR_ZONE_A_BASE64_API_KEY"
ota_password_zone_a: "YOUR_ZONE_A_OTA_PASSWORD"

api_encryption_key_zone_b: "REPLACE_WITH_YOUR_ZONE_B_BASE64_API_KEY"
ota_password_zone_b: "YOUR_ZONE_B_OTA_PASSWORD"

owm_forecast_url: "https://api.openweathermap.org/data/2.5/forecast?lat=YOUR_LAT&lon=YOUR_LON&units=metric&cnt=8&appid=YOUR_API_KEY"
